export type tCategory =
  | 'All'
  | 'United States'
  | 'United Kingdom'
  | 'Netherlands'
  | 'Australia'
  | 'India'
  | 'Türkiye'
  | 'Sweden'
  | 'Finland'
  | 'Iran'
  | 'China'
  | 'Canada'
  | 'Seal Logo'
  | 'Symbolic Logo'
  | 'Wordmark Logo'
  | 'Combination Logo';
